// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNIGUTmTdXBLqXxm_mM6CNghkG2p7eZnQ',
    appId: '1:740439076635:web:08248147e8d2efa47d6dbe',
    messagingSenderId: '740439076635',
    projectId: 'ukm-flutter-t',
    authDomain: 'ukm-flutter-t.firebaseapp.com',
    storageBucket: 'ukm-flutter-t.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBORCbFdT0or6uLgcL5oStY5dsZ_gVC1uI',
    appId: '1:740439076635:android:2808986e811893167d6dbe',
    messagingSenderId: '740439076635',
    projectId: 'ukm-flutter-t',
    storageBucket: 'ukm-flutter-t.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-0j36STMcwqfmvOIqqEJOHzI3iNAwFas',
    appId: '1:740439076635:ios:0fe954ee6d01332b7d6dbe',
    messagingSenderId: '740439076635',
    projectId: 'ukm-flutter-t',
    storageBucket: 'ukm-flutter-t.appspot.com',
    iosClientId: '740439076635-385nlm3beqk54pja4rk30o4hsiaecosh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-0j36STMcwqfmvOIqqEJOHzI3iNAwFas',
    appId: '1:740439076635:ios:d32595fdded0b1437d6dbe',
    messagingSenderId: '740439076635',
    projectId: 'ukm-flutter-t',
    storageBucket: 'ukm-flutter-t.appspot.com',
    iosClientId: '740439076635-gfu1aqd7m2cg5vdg8hdvifst8mt5316v.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
